estetica/core/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('cadastro_servico/', cadastro_servico, name='cadastro_servico'),
    path('servico_dia/', servico_dia, name='servico_dia'),
    path('regulamento/', regulamento, name='regulamento'),
    path('pagina_servico/', pagina_servico, name='pagina_servico'),
    path('local/', local, name='local'),
    path('listagem/', listagem, name='listagem')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

estetica/estetica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"))
]

estetica/core/models.py
from django.db import models

# Create your models here.

class Servico(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome
    

class Agenda(models.Model):
    nome = models.CharField(max_length=50)
    data = models.DateField()
    telefone = models.CharField(max_length=14)
    posicao = models.IntegerField()
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE)

class Servico_dia(models.Model):
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE)
    data = models.DateField()

estetica/core/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import DateInput
from .models import *
from .views import *

class FormServico(ModelForm):
    class Meta:
        model = Servico
        fields = '__all__'

class FormServicoDia(ModelForm):
    class Meta:
        model = Servico_dia
        fields = '__all__'
        widgets = {
            "servico": forms.Select(attrs={'class': 'select'}),
            "data": forms.DateInput(attrs={'class': 'data', 'type': 'date'})
        }

estetica/core/views.py
from django.shortcuts import render
from .models import *
from .forms import *
# Create your views here.

def cadastro_servico(request):
    if request.method == 'POST':
       form = FormServico(request.POST)
       if form.is_valid():
            form.save()
    form = FormServico()
    context = {
        'form': form,
    }
    return render(request, 'cadastro_servico.html', context)

def servico_dia(request):
    if request.method == 'POST':
       form = FormServicoDia(request.POST)
       if form.is_valid():
            form.save()
    form = FormServicoDia()
    context = {
        'form': form,
    }
    return render(request, 'servico_dia.html', context)

def regulamento(request):
     return render(request, 'regulamento.html')

def pagina_servico(request):
     return render(request, 'pagina_servico.html')

def local(request):
     return render(request, 'local.html')

def listagem(request):
     return render(request, 'listagem.html')

estetica/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block css %}{% endblock %}
    <style>
        .margemcima a {
            text-decoration: none;
            color: #888888
        }
    </style>
</head>
<body>
    <header class="retangulo1">
        <img class="logo" src="{% static 'Group32.svg' %}" alt="a">
        <div class="margemcima">
            <a href="">Serviços</a>
            <a href="">Localização</a>
            <a href="">Sobre</a>
            <div class="botoes">
                <a><img width="31px" height="31px" src="{% static 'carrinho.png' %}" alt="carrinho"></a>
                <a><img width="31px" height="31px" src="{% static 'conta.png' %}" alt=""></a>
            </div>
        </div>
    </header>
    {% block main %}
    {% endblock %}
    <footer class="retangulo2">
        <img src="{% static 'telefone.png' %}" alt="telefone">
        <p>(84) 99999-9999</p>
    </footer>
</body>
</html>

estetica/core/templates/cadastro_servico.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    * {
        margin: 0;
        padding: 0;
    }

    body {
        display: flex;
        flex-direction: column;
        height: 100vh;
        justify-content: space-between;
    }

    .retangulo1 {
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.705);
        -webkit-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.63);
        -moz-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.92);
        width: 100%;
        /* Largura do retângulo */
        /* Altura do retângulo */
        background-color: #ffffff;
        /* Cor de fundo do retângulo (pode ser alterada) */
        text-align: right;
    }

    .retangulo2 {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 30px;
        /* Altura do retângulo */
        background-color: #b5babd;
        /* Cor de fundo do retângulo (pode ser alterada) */
    }

    .margemcima {
        display: flex;
        gap: 177px;
        margin-right: 31px;
    }

    .carrinho {
        margin-left: auto;
        margin-right: 30px;
        color: black;
    }

    .botoes {
        display: flex;
        gap: 19px;
        margin-left: 215px;
        border-left: solid 1px #c3c3c3;
        padding-left: 31px;
    }

    .logo {
        margin-top: 25px;
        margin-bottom: 25px;
        margin-left: 76px;
    }

    .titulo-pagina {
        margin-top: 10px;
        margin-bottom: 11px;
        font-size: 48px;
        align-self: center;
    }

    .conteudo {
        align-self: center;
        display: flex;
        flex-direction: column;
    }

    .formulario {
        display: flex;
        flex-direction: column;
        padding: 156px 100px 92px;
        background-color: #B3C2F566;
        border-radius: 25px;
        margin-bottom: 38px;
        align-items: center;
    }

    .label-cadastro {
        font-size: 26px;
    }

    .input-cadastro {
        border-radius: 25px;
        padding: 10px 30px;
        font-size: 28px;
        text-align: center;
        margin-top: 10px;
        margin-bottom: 113px;
    }

    .btn-form {
        padding: 10px 47px;
        border-radius: 25px;
        border: none;
        font-size: 24px;
        background-color: #52D912;
    }

    .btn-form:hover {
        cursor: pointer;
    }

    .margemcima a {
        font-size: 28px;
    }
</style>

<body>
    <header class="retangulo1">
        <img class="logo" src="{% static 'Group32.svg' %}" alt="a">
        <div class="margemcima">
            <a>Serviços</a>
            <a>Localização</a>
            <a>Sobre</a>
            <div class="botoes">
                <a><img width="31px" height="31px" src="{% static 'carrinho.png' %}" alt="carrinho"></a>
                <a><img width="31px" height="31px" src="{% static 'conta.png' %}" alt=""></a>
            </div>
        </div>
    </header>
    <main class="conteudo">
        <h3 class="titulo-pagina">Adicionar Serviços</h3>
        <form action="/cadastro_servico/" method="post" class="formulario">
            {% csrf_token %}
            <label for="id_nome" class="label-cadastro">Serviço</label>
            <input class="input-cadastro" type="text" name="nome" maxlength="50" required="" id="id_nome" placeholder="Nome">
            <button class="btn-form" type="submit">confirmar</button>
        </form>
    </main>
    <footer class="retangulo2">
        <img src="{% static 'telefone.png' %}" alt="telefone">
        <p>(84) 99999-9999</p>
    </footer>
</body>

</html>

estetica/core/templates/listagem.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

    * {
        margin: 0;
        padding: 0;
        font-family: 'Poppins', sans-serif;
    }

    body {
        display: flex;
        flex-direction: column;
        height: 100vh;
        justify-content: space-between;
    }

    .retangulo1 {
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.705);
        -webkit-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.63);
        -moz-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.92);
        width: 100%;
        background-color: #ffffff;
        text-align: right;
    }

    .retangulo2 {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 30px;
        background-color: #b5babd;
    }

    .imagem-senac {
        width: 781px;
        height: 530px;
    }

    .margemcima {
        display: flex;
        gap: 177px;
        margin-right: 31px;
    }

    .carrinho {
        margin-left: auto;
        margin-right: 30px;
        color: black;
    }

    .botoes {
        display: flex;
        gap: 19px;
        margin-left: 215px;
        border-left: solid 1px #c3c3c3;
        padding-left: 31px;
    }

    .logo {
        margin-top: 25px;
        margin-bottom: 25px;
        margin-left: 76px;
    }

    .titulo-pagina {
        margin-top: 10px;
        margin-bottom: 11px;
        font-size: 48px;
        align-self: center;
    }

    .conteudo {
        display: flex;
        justify-content: center;
        border-radius: 25px;
        margin-bottom: 30px;
        justify-content: space-between;
        margin-right: 100px;
        margin-bottom: 22.5px;
        margin-left: 90px;
        font-size: 22.5px;
        align-items: center;
        justify-content: space-around;
    }

    .formulario {
        display: flex;
        flex-direction: column;
        padding: 50px 1px 0px;
        background-color: #B3C2F566;
        border-radius: 25px;
        margin-bottom: 38px;
        align-items: center;
    }

    .label-cadastro {
        font-size: 26px;
    }

    .input-cadastro {
        border-radius: 25px;
        padding: 10px 30px;
        font-size: 28px;
        text-align: center;
        margin-top: 10px;
        margin-bottom: 113px;
    }

    .btn-form {
        padding: 10px 47px;
        border-radius: 25px;
        border: none;
        font-size: 24px;
        background-color: #52D912;
    }

    .btn-form:hover {
        cursor: pointer;
    }

    .margemcima a {
        font-size: 28px;
    }

    .texto-cima {
        display: flex;
        justify-content: space-around;
        margin-top: -350px;
        margin-right: 275px;
        font-size: 20px;
        font-weight: 600;
    }

    table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 20px;
        margin-left: 48px;
        margin-right: 48px;
        margin-bottom: 20px;
        /* Adjust margin-bottom as needed */
        border-radius: 10px;
    }

    th,
    td {
        background-color: #B3C2F5;
        border: 1px solid #ffffff;
        text-align: left;
        padding: 8px;
    }

    th {
        background-color: #fff;
    }

    .btn-group {
        display: flex;
        justify-content: space-around;
    }

    .btn {
        padding: 8px 20px;
        cursor: pointer;
        background-color: #18B21E;
        border-radius: 10px;
        color: #ffffff;
    }

    .btn2 {
        background-color: #538DFF;
    }

    .btn3 {
        background-color: #FF5353;
    }

    .labels {
        display: flex;
        justify-content: space-around;
        margin-top: -340px;
        margin-right: 100px;
        font-size: 20px;
        font-weight: 600;
    }

    .servico {
        margin-right: 250px;
    }

    .todes {
        text-align: center;
    }
</style>
{% endblock %}

{% block header %}{% endblock %}
{% block main %}
<main>

    <table>
        <tbody>
            <tr>
                <th>Nome</th>
                <th>Data</th>
                <th>Telefone</th>
                <th>Posição</th>
                <th class="servico">Serviço</th>
                <th></th>
            </tr>
            <tr>
                <td class="todes">Exemplo 1</td>
                <td class="todes">01/01/2024</td>
                <td class="todes">(123) 456-7890</td>
                <td class="todes">Posição 1</td>
                <td class="todes">Serviço A</td>
                <td>
                    <button class="btn" onclick="iniciarAcao()">Iniciar</button>
                </td>
                <td>
                    <button class="btn btn2" onclick="terminarAcao()">Terminar</button>
                </td>
                <td>
                    <button class="btn btn3" onclick="apagarAcao()">Apagar</button>
                </td>
            </tr>
            <!-- Add more rows as needed -->
        </tbody>
    </table>
</main>
{% endblock %}
{% block footer %}{% endblock %}

estetica/core/templates/local.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

    * {
        margin: 0;
        padding: 0;
        font-family: 'Poppins', sans-serif;
    }

    body {
        display: flex;
        flex-direction: column;
        height: 100vh;
        justify-content: space-between;
    }

    .retangulo1 {
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.705);
        -webkit-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.63);
        -moz-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.92);
        width: 100%;
        /* Largura do retângulo */
        /* Altura do retângulo */
        background-color: #ffffff;
        /* Cor de fundo do retângulo (pode ser alterada) */
        text-align: right;
    }

    .retangulo2 {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 30px;
        /* Altura do retângulo */
        background-color: #b5babd;
        /* Cor de fundo do retângulo (pode ser alterada) */
    }

    .margemcima {
        display: flex;
        gap: 177px;
        margin-right: 31px;
    }

    .carrinho {
        margin-left: auto;
        margin-right: 30px;
        color: black;
    }

    .botoes {
        display: flex;
        gap: 19px;
        margin-left: 215px;
        border-left: solid 1px #c3c3c3;
        padding-left: 31px;
    }

    .logo {
        margin-top: 25px;
        margin-bottom: 25px;
        margin-left: 76px;
    }

    .titulo-pagina {
        margin-top: 10px;
        margin-bottom: 11px;
        font-size: 48px;
        align-self: center;

    }

    .conteudo {
        display: flex;
        align-items: center;
        justify-content: space-around;
    }

    .formulario {
        display: flex;
        flex-direction: column;
        padding: 156px 100px 92px;
        background-color: #B3C2F566;
        border-radius: 25px;
        margin-bottom: 38px;
        align-items: center;
    }

    .label-cadastro {
        font-size: 26px;
    }

    .input-cadastro {
        border-radius: 25px;
        padding: 10px 30px;
        font-size: 28px;
        text-align: center;
        margin-top: 10px;
        margin-bottom: 113px;
    }

    .btn-form {
        padding: 10px 47px;
        border-radius: 25px;
        border: none;
        font-size: 24px;
        background-color: #52D912;
    }

    .btn-form:hover {
        cursor: pointer;
    }

    .margemcima a {
        font-size: 28px;
    }

    .foto {
        width: 781px;
        height: 530px;
        display: flex;
    }

    .texto {
        font-size: 23.5px;
        text-align: left;
    }
</style>
{% endblock %}

{% block header %}{% endblock %}
{% block main %}

<main class="conteudo">
    <div class="foto">
        <img src="{% static 'senacara.jpg' %}" alt="center">
    </div>

    <div class="texto">
        <h1 class="Local">Local</h1>
        <p>Rua Marinete Francisca Nunes, s/n - Brasiliana, Arapiraca - AL, 57310-510</p>
        <br>
        <h1 class="Horário de atendimento">Horario de atendimento</h1>
        <p>De segunda a sábado de 08h às 19h.</p>
    </div>
    </form>
</main>
{% endblock %}
{% block footer %}{% endblock %}

estetica/core/templates/pagina_servico.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

    * {
        margin: 0;
        padding: 0;
        font-family: 'Poppins', sans-serif;
    }

    body {
        display: flex;
        flex-direction: column;
        height: 100vh;
        justify-content: space-between;
    }

    .retangulo1 {
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.705);
        -webkit-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.63);
        -moz-box-shadow: -2px 4px 15px -3px rgba(0, 0, 0, 0.92);
        width: 100%;
        background-color: #ffffff;
        text-align: right;
    }

    .retangulo2 {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 30px;
        background-color: #b5babd;
    }

    .margemcima {
        display: flex;
        gap: 177px;
        margin-right: 31px;
    }

    .carrinho {
        margin-left: auto;
        margin-right: 30px;
        color: black;
    }

    .botoes {
        display: flex;
        gap: 19px;
        margin-left: 215px;
        border-left: solid 1px #c3c3c3;
        padding-left: 31px;
    }

    .logo {
        margin-top: 25px;
        margin-bottom: 25px;
        margin-left: 76px;
    }

    .titulo-pagina {
        margin-top: 10px;
        margin-bottom: 11px;
        font-size: 48px;
        align-self: center;
    }

    .conteudo {
        align-self: center;
        display: flex;
        flex-direction: column;
    }

    .formulario {
        display: flex;
        flex-direction: column;
        padding: 156px 100px 92px;
        background-color: #B3C2F566;
        border-radius: 25px;
        margin-bottom: 38px;
        align-items: center;
    }

    .label-cadastro {
        font-size: 26px;
    }

    .input-cadastro {
        border-radius: 25px;
        padding: 10px 30px;
        font-size: 28px;
        text-align: center;
        margin-top: 10px;
        margin-bottom: 113px;
    }

    .btn-form {
        width: 216px;
        height: 66px;
        border-radius: 20px;
        font-size: 24px;
        background-color: #52D912;
        border: solid 1px #888888;
        color: #ffffff;
    }

    .btn-form:hover {
        cursor: pointer;
    }

    .margemcima a {
        font-size: 28px;
    }

    .imagem {
        width: 1175px;
        height: 558px;
    }

    .nomeladoimagem {
        display: flex;
        flex-direction: column;
    }

    .textoladoimagem {
        display: flex;
        flex-direction: column;
        margin-top: 17.5px;
    }

    .filtrar {
        align-self: flex-end;
        margin-right: 99px;
        margin-bottom: 22.5px;
    }

    .conteudo-imagem-texto {
        display: flex;
    }

    .textoladoimagem p {
        max-width: 460px;
    }

    .textoladoimagem h1 {
        font-size: 48px;
    }

    .imagem-procedimento {
        margin-left: 30px;
        margin-right: 61px;
    }

    .preco {
        display: flex;
        justify-content: space-between;
        margin-top: 200px;
    }

    .valor {
        color: #52D912;
        font-size: 24px;
        font-weight: 700;
    }

    .por {
        font-size: 20px;
        font-weight: 500;
        margin-top: 10px;
    }

    body {
        margin: 0;
        font-family: 'Arial', sans-serif;
    }

    #overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.7);
        z-index: 2;
    }

    #sidebar {
        height: 100%;
        width: 0;
        opacity: 0;
        position: fixed;
        z-index: 3;
        top: 0;
        right: 0;
        background-color: #fff;
        overflow-x: hidden;
        transition: width 0.5s, opacity 0.5s;
        padding-top: 60px;
        color: white;
        visibility: hidden;
    }

    #sidebar.open {
        width: 25%;
        opacity: 1;
        visibility: visible;
    }

    #sidebar a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 18px;
        color: #818181;
        display: block;
        transition: 0.3s;
    }

    #sidebar a:hover {
        color: #f1f1f1;
    }

    #sidebar .closebtn {
        position: fixed;
        top: 0px;
        right: 25px;
        font-size: 70px;
    }

    #sidebar hr {
        margin: 10px 0;
        border: 1px solid #818181;
    }

    #main {
        transition: margin-right 0.5s;
        padding: 16px;
    }

    #bookingDetails {
        text-align: center;
    }

    #serviceName {
        margin-bottom: 10px;
        text-align: left;
        font-size: 14px;
        color: #818181;
    }

    #serviceImage {
        width: 300px;
        height: 230px;
        background-color: #FFF4FE;
        margin: 10px auto;
        border-radius: 10px;
        margin-bottom: 400px;
    }

    #discountCode {
        margin-bottom: 0px;
        margin-top: 180px;
        padding: 8px;
        width: 60%;
        border-radius: 15px;
        display: inline-block;
    }

    #applyButton {
        margin: 10px 0;
        padding: 8px;
        background-color: #F3BD30;
        color: white;
        border: none;
        border-radius: 15px;
        cursor: pointer;
        display: inline-block;
        width: 30%;
    }

    #totalAmount {
        margin: 0px 25px;
        margin-top: -12px;
        margin-bottom: -22px;
        padding: 8px;
        width: 80%;
        border-radius: 5px;
        display: flex;
        justify-content: space-between;
        font-size: 20px;
        color:#424242
    }

    #confirmButton {
        margin-top: 0px;
        padding: 10px;
        background-color: #52D912;
        color: white;
        border: none;
        border-radius: 25px;
        cursor: pointer;
        width: 320px;
        height: 50px;
    }

    .carrinhotitulo {
        display: flex;
        margin-left: 45px;
        margin-top: -20px;
        margin-bottom: 35px;
        font-size: 25px;
        color: #424242;
    }

    .form-sidebar {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }
    
    .form-sidebar-inputs {
        margin: 55px 0 344px;
        display: flex;
        flex-direction: column;
        gap: 27px;
        align-items: flex-end;
        margin-right: 45px;
    }

    .input-group {
        color: #000;
    }

    .input-group input {
        padding-left: 12px;
        padding-top: 8px;
        padding-bottom: 8px;
        border: solid 3px #9f9f9f;
        border-radius: 40px;
        width: 306px;
    }

    .form-sidebar-button {
        box-shadow: 0px -4px 4px #00000010;
        padding-top: 45px;
        padding-bottom: 45px;
    }

    .form-sidebar-button button {
        padding: 16px 110px;
        border-radius: 25px;
        border: none;
        background-color: #52D912;
        color: #fff;
        font-weight: 600;
        cursor: pointer;
    }
</style>
{% endblock %}

{% block header %}{% endblock %}
{% block main %}
<main>
    <div id="overlay"></div>

    <div class="nomeladoimagem">
        <img class="filtrar" src="{% static 'filtrar.svg' %}" alt="a">
        <div class="conteudo-imagem-texto">
            <img class="imagem-procedimento" src="{% static 'massagem.png' %}" alt="a">
            <div class="textoladoimagem">
                <h1>Massagem Terapêutica</h1>
                <p>A massagem terapêutica busca tratar as dores que provêm de vários fatores dentre esses, o estresse no
                    trabalho causando forte tensão emocional, posturas inadequadas, posicionamento prolongado. O início
                    das dores pode ser através de nódulos, localizada em algum local do corpo que tem musculatura
                    formada pelas tensões.</p>
                <div class="preco">
                    <p class="por">Por <span class="valor">R$00,00</span></p>
                    <button class="btn-form" type="submit" onclick="openNav()">Agendar</button>
                </div>
            </div>
        </div>

        <div id="sidebar">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
            <div id="bookingDetails">
                <p class="carrinhotitulo">Informações pessoais</p>
                <hr>
                <form action="" class="form-sidebar">
                    <div class="form-sidebar-inputs">
                        <div class="input-group">
                            <label for="">CPF:</label>
                            <input type="text" name="cpf">
                        </div>
                        <div class="input-group">
                            <label for="">Fone:</label>
                            <input type="text" name="fone">
                        </div>
                        <div class="input-group">
                            <label for="">Nome:</label>
                            <input type="text" name="nome">
                        </div>
                    </div>
                    <div class="form-sidebar-button">
                        <button type="submit">Agendar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<script>
    function openNav() {
        document.getElementById("overlay").style.display = "block";
        document.getElementById("sidebar").classList.add('open');
    }

    function closeNav() {
        document.getElementById("overlay").style.display = "none";
        document.getElementById("sidebar").classList.remove('open');
    }
</script>
{% endblock %}
{% block footer %}{% endblock %}